# requiring the environment of Ruby 2.1.x
image: ruby:2.5.1

# add bundle cache to 'vendor' for speeding up builds
cache:
  paths:
    - vendor/

stages:
  - test
  - deploy

before_script:
  - apt-get update -qy
  - apt-get install -y nodejs # requires JS runtime
  - mkdir public
  - bundle install --jobs 4 --path vendor

review:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  before_script:
    - apt-get update -qy
    - apt-get install -y rsync
  cache: {}
  script:
    - rsync -av --delete public /srv/nginx/pages/$CI_BUILD_REF_NAME
  environment:
    name: review/$CI_BUILD_REF_NAME
    url: http://$CI_BUILD_REF_NAME.$APPS_DOMAIN
    on_stop: review_stop
  only:
    - branches
  except:
    - master
  tags:
    - nginx
    - review-apps

## Stop the review app
review_stop:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  before_script: []
  artifacts: {}
  cache: {}
  script:
    - rm -rf public /srv/nginx/pages/$CI_BUILD_REF_NAME
  dependencies: []
  when: manual
  environment:
    name: review/$CI_BUILD_REF_NAME
    action: stop
  only:
    - branches
  except:
    - master
  tags:
    - nginx
    - review-apps

# add a job called 'test' -> non-required
test:
  stage: test
  script:
    - bundle exec middleman build
  except:
    - master # the 'test' job will affect all branches expect 'master'

# the 'pages' job will deploy and build your site to the 'public' path
pages:
  stage: deploy
  script:
    - bundle exec middleman build --build-dir=public --verbose
  artifacts:
    paths:
      - public
  only:
    - master # this job will affect only the 'master' branch
