sudo: false

language: ruby

rvm:
  - 2.4.0

cache: bundler

script:
  - bash deploy.sh

before_deploy: git config --global user.email $USER_MAIL && git config --global user.name $USER_NAME
deploy:
  provider: pages
  skip_cleanup: true
  local_dir : public
  github_token: $GITHUB_TOKEN
  target_branch : gh-pages
  on:
    branch: master
